#!/bin/bash
. ./hooks/utils

ACTIVE=`cat ./hooks/ACTIVE | grep 0`

if [ "$ACTIVE" != "" ]; then
  log_info "commit-msg... no active"
  exit 0
fi

log_info "iniciando commit-msg..."
log_info "args: $@"

branch=`git status -b | grep branch`
isDevelop=`git status -sb | grep develop`
isMaster=`git status -sb | grep master`
isFeature=`git status -sb | grep feature`
featureName=`git status -sb | grep feature | awk '{print $2}' FS="/"`
isRelease=`git status -sb | grep release`
isHotfix=`git status -sb | grep hotfix`
log_info "branch: $branch"

message=`cat $1`
log_info "message: $message"

isMerge=`echo $message | grep Merge`

if [ "$isMerge" != "" ]; then
	log_info "is from merge..."
	git flow feature finish $featureName >> /tmp/git.log
fi

log_info "finalizando commit-msg"
