#!/bin/bash
. ./hooks/utils

log_info "iniciando commit-msg..."
log_info "args: $@"

branch=`git status -b | grep branch`
isDevelop=`git status -sb | grep develop`
isMaster=`git status -sb | grep master`
isFeature=`git status -sb | grep feature`
isRelease=`git status -sb | grep release`
isHotfix=`git status -sb | grep hotfix`
log_info "branch: $branch"

message=`cat $1`
log_info "message: $message"

log_info "finalizando commit-msg"
