#!/bin/bash
export DOT_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
echo iniciando commit-msg...
echo args: $@

branch=`git status -b | grep branch`
isDevelop=`git status -sb | grep develop`
isMaster=`git status -sb | grep master`
isFeature=`git status -sb | grep feature`
isRelease=`git status -sb | grep release`
isHotfix=`git status -sb | grep hotfix`
echo branch: $branch

message=`cat $1`
echo message: $message

echo finalizando commit-msg
