#!/bin/bash
. ./hooks/utils

ACTIVE=`cat ./hooks/ACTIVE | grep 0`

if [ "$ACTIVE" != "" ]; then
  log_info "post-merge... no active"
  exit 0
fi

log_info "iniciando post-merge..."
log_info "args: $@"
git status

branch=`git status -b | grep branch`
isDevelop=`git status -sb | grep develop`
isMaster=`git status -sb | grep master`
isFeature=`git status -sb | grep feature`
featureName=`git status -sb | grep feature | awk '{print $2}' FS="/"`
isRelease=`git status -sb | grep release`
isHotfix=`git status -sb | grep hotfix`
log_info "branch: $branch"

version=`cat package.json | grep version | awk '{print $2}' FS=":" | sed 's/[\"\,\ ]//g'`


hasRC=`echo $version | grep rc`
message=`cat "$(git rev-parse --show-toplevel)"/.git/COMMIT_EDITMSG`

log_info "$message"

hasMerge=`echo $message | grep "Merge"`

echo "" > "$(git rev-parse --show-toplevel)"/.git/COMMIT_EDITMSG

log_info "finalizando post-merge"
