#!/bin/bash
pwd
. ./hooks/utils

log_info probando....

echo iniciando post-checkout...
echo usando args: $@
git status

branch=`git status -b | grep branch`
echo usando branch: $branch

version=`git log -p $2 -1 package.json | grep "+  \"version" | awk '{print $2}' FS=":" | sed 's/[\,\"\ ]//g'`
echo usando version $version

#git checkout --ours package.json
#if [ "$1" != "$2" ]; then
#  echo commiting diffs...
#  npm version --no-git-tag-version patch
#  git add package.json
#  git commit -am "updating version before merge"
#fi

echo finalizando post-checkout
