#!/bin/bash
. ./hooks/utils

ACTIVE=`cat ./hooks/ACTIVE | grep 0`

if [ "$ACTIVE" != "" ]; then
  log_info "pre-commit... no active"
  exit 0
fi

log_info "iniciando pre-commit..."
log_info "args: $@"

branch=`git status -b | grep branch`
isDevelop=`git status -sb | grep develop`
isMaster=`git status -sb | grep master`
isFeature=`git status -sb | grep feature`
isRelease=`git status -sb | grep release`
isHotfix=`git status -sb | grep hotfix`
log_info "branch: $branch"

version=`cat package.json | grep version | awk '{print $2}' FS=":" | sed 's/[\"\,\ ]//g'`


hasRC=`echo $version | grep rc`
message=`cat "$(git rev-parse --show-toplevel)"/.git/COMMIT_EDITMSG`
log_info "$message"
isMerge=`echo $message | grep "Merge"`

if [ "$version" != "" ]; then
#   git tag -a "v$version" -m "`git log -1 --format=%s`"
  log_info "on version: $version"
  if [ "$isFeature" == "" ]; then
    log_info "no feature"
    if [ "$hasRC" == "" ]; then
      log_info "noRC"
      if [ "$isMerge" == "" ]; then
        log_info "no es un merge...."
        if [ "$isMaster" == "" ]; then
          npm version --no-git-tag-version patch
          git add package.json
        fi
      else
        if [ "$isMaster" != "" ]; then
          npm version --no-git-tag-version minor
          git add package.json
        fi
      fi
    else
      log_info "es una RC"
      v0=`echo $version | awk '{print $1}' FS='-rc'`
      log_info "v0 $v0"
      v=$((v+1))
      npm version --no-git-tag-version $v0
      npm version --no-git-tag-version patch
      git add package.json
    fi
  else
    log_info "feature"
    if [ "$hasRC" == "" ]; then
      log_info "noRC"
      npm version --no-git-tag-version $version-rc0
      git add package.json
    else
      log_info "es una RC"
      v0=`echo $version | awk '{print $1}' FS='rc'`
      log_info "v0 $v0"
      v=`echo $version | awk '{print $2}' FS='rc'`
      log_info "v $v"
      v=$((v+1))
      npm version --no-git-tag-version $v0'rc'$v
      git add package.json
    fi
  fi
fi

log_info "finalizando pre-commit"
