#!/bin/bash
. ./hooks/utils

ACTIVE=`cat ./hooks/ACTIVE | grep 0`

if [ "$ACTIVE" != "" ]; then
  log_info "pre-push... no active"
  exit 0
fi

log_info "iniciando pre-push..."
log_info "args: $@"

branch=`git status -b | grep branch`
isDevelop=`git status -sb | grep develop`
isMaster=`git status -sb | grep master`
isFeature=`git status -sb | grep feature`
isRelease=`git status -sb | grep release`
isHotfix=`git status -sb | grep hotfix`
log_info "branch: $branch"

if [ "$isMaster" != "" ]; then
  # git add package.json
  version=`cat package.json | grep version | awk '{print $2}' FS=":" | sed 's/[\"\,\ ]//g'`
  git tag $version master
  log_info "new version: $version"
  # git commit -m "updating master to version $version"
fi


log_info "finalizando pre-push"
